package parser

import (
	"strings"
	"testing"
)

const sampleIptablesSave = `# Generated by iptables-save v1.8.7
*filter
:INPUT ACCEPT [100:8000]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [250:18400]
:MY_CUSTOM_CHAIN - [0:0]
[50:4000] -A INPUT -p tcp -m multiport --dports 22,80,443 -m conntrack --ctstate NEW,ESTABLISHED -m comment --comment "allow ssh and web" -j ACCEPT
[10:800] -A INPUT -p icmp -m limit --limit 10/sec --limit-burst 5 -j ACCEPT
[5:320] -A INPUT -p tcp --dport 8443 -j DROP
COMMIT
*nat
:PREROUTING ACCEPT [30:1200]
:INPUT ACCEPT [10:400]
:OUTPUT ACCEPT [15:600]
:POSTROUTING ACCEPT [20:800]
[5:200] -A POSTROUTING -o eth0 -j MASQUERADE
COMMIT
`

func TestParseIptablesSave(t *testing.T) {
	rs, err := ParseIptablesSave(sampleIptablesSave)
	if err != nil {
		t.Fatalf("Erro inesperado no parse: %v", err)
	}

	if len(rs.Tables) != 2 {
		t.Fatalf("Esperava 2 tabelas (filter, nat), obteve %d", len(rs.Tables))
	}

	filterTable, ok := rs.Tables["filter"]
	if !ok {
		t.Fatalf("Tabela filter não encontrada")
	}

	if len(filterTable.Chains) != 4 {
		t.Errorf("Esperava 4 chains em filter, obteve %d", len(filterTable.Chains))
	}

	if len(filterTable.Rules) != 3 {
		t.Fatalf("Esperava 3 regras em filter, obteve %d", len(filterTable.Rules))
	}

	// Verifica regra 1
	r1 := filterTable.Rules[0]
	if r1.Protocol != "tcp" {
		t.Errorf("Esperava proto tcp, obteve %s", r1.Protocol)
	}
	if r1.DstPorts != "22,80,443" {
		t.Errorf("Esperava dports 22,80,443, obteve %s", r1.DstPorts)
	}
	if r1.PacketCounter != 50 || r1.ByteCounter != 4000 {
		t.Errorf("Contadores errados: %d:%d", r1.PacketCounter, r1.ByteCounter)
	}
	if r1.Target != "ACCEPT" {
		t.Errorf("Esperava target ACCEPT, obteve %s", r1.Target)
	}

	// Canonical hash deve ser determinístico
	h1 := rs.CanonicalHash()
	h2 := rs.CanonicalHash()
	if h1 == "" || h1 != h2 {
		t.Errorf("Hash canônico falhou na consistência: %s vs %s", h1, h2)
	}

	// Formatação iptables-restore
	formatted := rs.FormatIptablesRestore(true)
	if !strings.Contains(formatted, "*filter") || !strings.Contains(formatted, "*nat") {
		t.Errorf("FormatIptablesRestore omitiu tabelas essenciais")
	}

	// Verifica detecção de risco lockout
	warnings := InspectSafetyHeuristics(filterTable.Rules, 8443, 22)
	if len(warnings) == 0 {
		t.Errorf("Deveria ter alertado sobre bloqueio da porta 8443 (DROP)")
	}
}
